### ISSUE TITLE
New logo for Lisp-Chat

### ISSUE THREAD

**Issue by reallinfo** [ryukinix/lisp-chat#14]
I wanted to contribute to Lisp-Chat. I designed a logo for Lisp-Chat. If you like it, I'll send you files and pr.

Do not hesitate to say if there is something you want to change. Color bla bla...

![lispchat](https://user-images.githubusercontent.com/36298335/38204006-d6b80d3a-36a9-11e8-809d-ba091b64c85b.jpg)

**Comment by ryukinix** [comment]
Can you change the base color of the logo to some more harmonic to the http://www.lisperati.com/logo.html logo?

**Comment by reallinfo** [comment]
Of course, which one?

![lisp](https://user-images.githubusercontent.com/36298335/38206287-7e0a1864-36b2-11e8-96b8-dcf9b44a0933.jpg)

**Comment by ryukinix** [comment]
(1) for the color simplicity, thank you

**Comment by reallinfo** [comment]
I will send pr and add the new logo, I should remove this from the readme?

![lsp](https://user-images.githubusercontent.com/36298335/38215915-e09c50cc-36d1-11e8-9f25-5ca27ee3042e.png)

**Comment by ryukinix** [comment]
Instead remove this warning, please, move this to the bottom of README and put the new logo on top (where is this warning for now).

I'll wait for the PR :D

**Comment by reallinfo** [comment]
okay, i sent pr :)
